services:
  # Type: web
  web:
    name: naterpay
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: MONNIFY_SECRET_KEY
        sync: false
      - key: MONNIFY_PUBLIC_KEY
        sync: false
      - key: MONNIFY_API_KEY
        sync: false
      - key: MONNIFY_CONTRACT_CODE
        sync: false
      - key: VTPASS_USERNAME
        sync: false
      - key: VTPASS_PASSWORD
        sync: false
      - key: VTPASS_PUBLIC_KEY
        sync: false
      - key: VTUGATE_API_KEY
        sync: false
